### PR TITLE
Adds support for auto-detecting the location of highlight

### PR DESCRIPTION
**Pull request by saagarjha**
The plugin now searches for highlight using “`which highlight`” and falls
back on `/opt/local/bin/highlight`.

### CODE REVIEW

**Comment by anthonygelibert** [comment]
Thank you!

**Comment by saagarjha** [comment]
Quick question: Could you ask the homebrew cask maintainers to update? The main reason I created this was because it didn't work when installing from homebrew.

**Comment by anthonygelibert** [comment]
I had a discussion with them on this specific point: https://github.com/caskroom/homebrew-cask/pull/17361.

I will ask them to update…

**Comment by tsparber** [comment]
Should I update to 2.0.6b4?
btw anyone can request a cask file update via PR (I'm also not a maintainer of homebrew-cask).

Infos about [updating a cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

**Comment by saagarjha** [comment]
Sure, I'll try to create a pull request. I'll get rid of the postflight requirement as well, since it's built in now.

**Comment by saagarjha** [comment]
@tsparber I can't seem to get `cask-repair --pull origin --push $github_user $outdated_cask` to work, some error about not having access rights?

**Pull request merged**
