### PR TITLE
Added direct support for json files.

### PR DESCRIPTION
**Pull request by kwillick**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/anthonygelibert/QLColorCode/pull/9" target="_blank">ReviewNinja

**Comment by anthonygelibert** [comment]
It's in the commit fc4bba885a3cedaebade1d5f0fdd80641113d9a1.

**Comment by kwillick** [comment]
Thanks.

**Comment by anthonygelibert** [comment]
Thanks to you!

**Pull request closed without merging**
